// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// NBmix_s1_EM_g_Rcpp
Rcpp::List NBmix_s1_EM_g_Rcpp(const Eigen::VectorXd& N, const Eigen::VectorXd& E, Eigen::VectorXd& h, Eigen::VectorXd& grid, double alpha, int maxi, double eps, bool dirichlet);
RcppExport SEXP _pvEBayes_NBmix_s1_EM_g_Rcpp(SEXP NSEXP, SEXP ESEXP, SEXP hSEXP, SEXP gridSEXP, SEXP alphaSEXP, SEXP maxiSEXP, SEXP epsSEXP, SEXP dirichletSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type N(NSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type E(ESEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type h(hSEXP);
    Rcpp::traits::input_parameter< Eigen::VectorXd& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< int >::type maxi(maxiSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< bool >::type dirichlet(dirichletSEXP);
    rcpp_result_gen = Rcpp::wrap(NBmix_s1_EM_g_Rcpp(N, E, h, grid, alpha, maxi, eps, dirichlet));
    return rcpp_result_gen;
END_RCPP
}
// post_draw_gmix_cpp
NumericVector post_draw_gmix_cpp(const NumericVector& prior_shape, const NumericVector& prior_rate, const NumericVector& Qn, const IntegerMatrix& N, const NumericMatrix& E, int nsim);
RcppExport SEXP _pvEBayes_post_draw_gmix_cpp(SEXP prior_shapeSEXP, SEXP prior_rateSEXP, SEXP QnSEXP, SEXP NSEXP, SEXP ESEXP, SEXP nsimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type prior_shape(prior_shapeSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type prior_rate(prior_rateSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type Qn(QnSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type N(NSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type E(ESEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    rcpp_result_gen = Rcpp::wrap(post_draw_gmix_cpp(prior_shape, prior_rate, Qn, N, E, nsim));
    return rcpp_result_gen;
END_RCPP
}
// post_draw_discrete_cpp
NumericVector post_draw_discrete_cpp(const NumericVector& grid, const NumericVector& esti_prior, const IntegerMatrix& N, const NumericMatrix& E, int nsim);
RcppExport SEXP _pvEBayes_post_draw_discrete_cpp(SEXP gridSEXP, SEXP esti_priorSEXP, SEXP NSEXP, SEXP ESEXP, SEXP nsimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type grid(gridSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type esti_prior(esti_priorSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type N(NSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type E(ESEXP);
    Rcpp::traits::input_parameter< int >::type nsim(nsimSEXP);
    rcpp_result_gen = Rcpp::wrap(post_draw_discrete_cpp(grid, esti_prior, N, E, nsim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pvEBayes_NBmix_s1_EM_g_Rcpp", (DL_FUNC) &_pvEBayes_NBmix_s1_EM_g_Rcpp, 8},
    {"_pvEBayes_post_draw_gmix_cpp", (DL_FUNC) &_pvEBayes_post_draw_gmix_cpp, 6},
    {"_pvEBayes_post_draw_discrete_cpp", (DL_FUNC) &_pvEBayes_post_draw_discrete_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_pvEBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
