# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NBmix_s1_EM_g_Rcpp <- function(N, E, h, grid, alpha, maxi, eps, dirichlet) {
    .Call(`_pvEBayes_NBmix_s1_EM_g_Rcpp`, N, E, h, grid, alpha, maxi, eps, dirichlet)
}

post_draw_gmix_cpp <- function(prior_shape, prior_rate, Qn, N, E, nsim) {
    .Call(`_pvEBayes_post_draw_gmix_cpp`, prior_shape, prior_rate, Qn, N, E, nsim)
}

post_draw_discrete_cpp <- function(grid, esti_prior, N, E, nsim) {
    .Call(`_pvEBayes_post_draw_discrete_cpp`, grid, esti_prior, N, E, nsim)
}

